### ISSUE TITLE
Allow to pull a chart from any branch

### ISSUE THREAD

**Issue by varditn** [travelaudience/armador#15]
### Expected Behaviour
When setting non-packaged charts in `prereqCharts`, `additionalValues`or `dependencies`. You could specify a git repo with specific branch or tag name and Armador will pull the chart from that specific change.
### Actual Behaviour
Armador pulls charts only from `master` branch.
### Example:
```
prereqCharts:
  - cert-manager:
      packaged: false
      repo: https://github.com/jetstack/cert-manager.git:[branch_name]
      pathToChart: helm/cert-manager
      overrideValueFiles:
        - values.yaml
```
