### ISSUE TITLE
Allow using dependecies/overrides with relative path

### ISSUE THREAD

**Issue by varditn** [travelaudience/armador#16]
### Expected Behaviour
Usage of a relative path as the location for the chart in `prereqCharts`, `additionalValues` or `dependencies` will use the local copy of the chart.
### Actual Behaviour
There is no option to use relative path for charts location, only git repo or chart repo.
### Example
```
prereqCharts:
  - cert-manager:
      packaged: false
      pathToChart: ./helm/cert-manager
      overrideValueFiles:
        - values.yaml
```
